language: node_js
sudo: false
node_js:
  - '0.12'
  - '4'
  - '5'
before_install:
  # Prevent Bower from asking questions.
  - export CI=true
  # Log HTTP requests
  - npm config set loglevel http
install:
  - time npm install
