language: node_js
dist: trusty
sudo: false
node_js:
  - '4.0'
  - '4'
  - '6'
  - '8'
  - '10'
before_install:
  # Prevent Bower from asking questions.
  - export CI=true
  # Log HTTP requests
  - npm config set loglevel http
install:
  - time npm install
